FROM node:8-alpine as build-stage
WORKDIR /app
ADD ./frontend /app
RUN npm install
COPY . .
RUN npm run build

FROM python:3.6-alpine as production-stage
WORKDIR /chalan
ADD . /chalan
COPY --from=build-stage /app/dist /chalan/frontend/dist

RUN apk add --no-cache tzdata
ENV TZ America/Mexico_City

RUN apk update && apk add nginx && rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.chalan-dev.conf /etc/nginx/conf.d/

RUN pip install -r requirements/dev.txt