FROM python:3.6-alpine
WORKDIR /chalan
COPY . .

RUN apk add --no-cache tzdata
ENV TZ America/Mexico_City

RUN apk update && apk add nginx && rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.chalan-dev.conf /etc/nginx/conf.d/

RUN pip install -r requirements/dev.txt