version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/chalan
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:8000
      - 443:443
    env_file: .env.prod
    restart: always
    command: sh -c "npm install --unsafe-perm --prefix frontend && npm run build --prefix frontend & while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;' & gunicorn -b 0.0.0.0:8001 --access-logfile - --error-logfile - chalan:app"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
