version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/chalan
    ports:
      - 80:8000
    env_file: .env.prod
    restart: always
    command: sh -c "nginx -g 'daemon off;' & gunicorn -b 0.0.0.0:8001 --access-logfile - --error-logfile - chalan:app"
