version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/chalan
    ports:
      - 80:8000
    env_file: .env.prod
    restart: always
    links:
      - db:dbserver
    command: sh -c "nginx -g 'daemon off;' & gunicorn -b 0.0.0.0:8001 --access-logfile - --error-logfile - chalan:app"
  db:
    image: "mysql/mysql-server:5.7"
    ports:
      - "3307:3306"
    env_file: .env.mysql.prod
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    restart: always
