FROM node:18-alpine as react-build-stage
WORKDIR /app
COPY /frontend-react/package.json ./
RUN npm install
COPY /frontend-react .
ARG NEXT_PUBLIC_PLACES_API_KEY
ENV NEXT_PUBLIC_PLACES_API_KEY=$NEXT_PUBLIC_PLACES_API_KEY
ARG NEXT_PUBLIC_CHAT_TENANT_ID
ENV NEXT_PUBLIC_CHAT_TENANT_ID=$NEXT_PUBLIC_CHAT_TENANT_ID
ARG NEXT_PUBLIC_CHAT_API_URL
ENV NEXT_PUBLIC_CHAT_API_URL=$NEXT_PUBLIC_CHAT_API_URL
ENV NODE_OPTIONS=--max-old-space-size=4096
RUN npm run build

FROM node:18-alpine
WORKDIR /chalan/frontend-react-standalone
COPY --from=react-build-stage /app/.next/standalone ./
COPY --from=react-build-stage /app/.next/static ./.next/static
COPY --from=react-build-stage /app/public ./public
