FROM python:3.6-alpine

WORKDIR /chalan
ADD . /chalan

RUN apk update && apk add nginx && rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.chalan.conf /etc/nginx/conf.d/

RUN pip install -r requirements/prod.txt