version: '3'
services:
  web:
    build: .
    volumes:
      - .:/chalan
    ports:
      - 8001:5000
    env_file: .env
    restart: always
    links:
      - db:dbserver
    command: flask run --host 0.0.0.0
  db:
    image: "mysql/mysql-server:5.7"
    ports:
      - "3307:3306"
    env_file: .env-mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    restart: always
