FROM node:8-alpine as build-stage
WORKDIR /chalan
COPY /frontend .
RUN npm install && npm run build

FROM python:3.6-alpine as production-stage
WORKDIR /chalan
COPY . .
COPY --from=build-stage /chalan/dist /chalan/frontend/dist
# RUN ls -la && cd frontend && ls -la && cd dist && ls -la

RUN apk add --no-cache tzdata
ENV TZ America/Mexico_City

RUN apk update && apk add nginx && rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.chalan-dev.conf /etc/nginx/conf.d/

RUN pip install -r requirements/dev.txt