"""empty message

Revision ID: 042bf0b5e323
Revises: d0e7265746f7
Create Date: 2024-02-07 13:42:20.533182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042bf0b5e323'
down_revision = 'd0e7265746f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lu_quotation_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    lu_quotation_status = sa.table('lu_quotation_status', sa.Column('id'), sa.Column('status'))
    op.bulk_insert(
        lu_quotation_status,
        [
            {
                'id': 1,
                'status': 'active',
            },
            {
                'id': 2,
                'status': 'selected',
            },
            {
                'id': 3,
                'status': 'cancelled',
            }
        ]
    )

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_status_id', sa.Integer(), server_default=sa.text("'1'"), nullable=False))
        batch_op.create_foreign_key('fk_quotations_lu_quotation_status', 'lu_quotation_status', ['quotation_status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quotations_lu_quotation_status', type_='foreignkey')
        batch_op.drop_column('quotation_status_id')

    op.drop_table('lu_quotation_status')
    # ### end Alembic commands ###
