"""empty message

Revision ID: 3b4f12746723
Revises: 
Create Date: 2023-07-05 13:07:26.917441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b4f12746723'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sepomex')
    with op.batch_alter_table('carrier_company', schema=None) as batch_op:
        batch_op.alter_column('rfc',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=12),
               nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=45),
               nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('comments',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('comments',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('active',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('driver_fee',
               existing_type=mysql.INTEGER(display_width=10),
               comment=None,
               existing_comment='base load price',
               existing_nullable=False)
        batch_op.alter_column('loader_fee',
               existing_type=mysql.INTEGER(display_width=10),
               comment=None,
               existing_comment='fee per loader',
               existing_nullable=False)
        batch_op.alter_column('loaders_quantity',
               existing_type=mysql.INTEGER(display_width=2),
               comment=None,
               existing_comment='quantity of loaders',
               existing_nullable=False)
        batch_op.alter_column('weight',
               existing_type=mysql.VARCHAR(length=45),
               comment=None,
               existing_comment='weight in kilograms',
               existing_nullable=True)
        batch_op.alter_column('active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('weight',
               existing_type=mysql.VARCHAR(length=45),
               comment='weight in kilograms',
               existing_nullable=True)
        batch_op.alter_column('loaders_quantity',
               existing_type=mysql.INTEGER(display_width=2),
               comment='quantity of loaders',
               existing_nullable=False)
        batch_op.alter_column('loader_fee',
               existing_type=mysql.INTEGER(display_width=10),
               comment='fee per loader',
               existing_nullable=False)
        batch_op.alter_column('driver_fee',
               existing_type=mysql.INTEGER(display_width=10),
               comment='base load price',
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               nullable=False)
        batch_op.alter_column('comments',
               existing_type=sa.String(length=500),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('comments',
               existing_type=sa.String(length=500),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('carrier_company', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=45),
               type_=mysql.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('rfc',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=13),
               nullable=False,
               existing_server_default=sa.text("''"))

    op.create_table('sepomex',
    sa.Column('id', mysql.MEDIUMINT(display_width=8, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_estado', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('id_municipio', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('municipio', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('ciudad', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('zona', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('cp', mysql.MEDIUMINT(display_width=9), autoincrement=False, nullable=False),
    sa.Column('asentamiento', mysql.VARCHAR(length=70), nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
