"""empty message

Revision ID: 74082ee598d6
Revises: 162f7f90aa2c
Create Date: 2024-04-10 18:34:54.591537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74082ee598d6'
down_revision = '162f7f90aa2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    lu_services_table = op.create_table('lu_services',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('service', sa.String(length=50), nullable=True),
        sa.Column('description', sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(
        lu_services_table,
        [
            {
                "service": "packaging",
                "description": "Packaging service required by customers",
            },
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lu_services')
    # ### end Alembic commands ###
