"""empty message

Revision ID: ecb0efa87e8a
Revises: 74082ee598d6
Create Date: 2024-04-10 18:43:25.943075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb0efa87e8a'
down_revision = '74082ee598d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_services',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('service_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
        sa.ForeignKeyConstraint(['service_id'], ['lu_services.id'], ),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_services')
    # ### end Alembic commands ###
