-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 13:36:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chalan
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `chalan` ;

-- -----------------------------------------------------
-- Schema chalan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chalan` DEFAULT CHARACTER SET utf8 ;
USE `chalan` ;

-- -----------------------------------------------------
-- Table `order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('carry_from', 'deliver_to') NOT NULL,
  `floor_number` INT(3) NULL,
  `order_id` INT NOT NULL,
  `street` VARCHAR(45) NULL,
  `interior_number` VARCHAR(45) NULL,
  `neighborhood` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zip_code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_order_details_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB CHARSET=utf8;


-- -----------------------------------------------------
-- Table `carrier_company`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `carrier_company` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) DEFAULT NULL,
  `rfc` varchar(12) NOT NULL DEFAULT '',
  `email` varchar(100) NOT NULL DEFAULT '',
  `address` varchar(200) NOT NULL DEFAULT '',
  `active` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB CHARSET=utf8;

INSERT INTO `carrier_company` (`id`, `name`, `rfc`, `email`, `address`, `active`)
VALUES
	(1, 'José Pablo Salgado Hernandez', 'test', 'salgadohernandezjosepablo482@gmail.com', 'Calle Lago Texcoco Manzana 7 Lote 379 Colonia Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1);


-- -----------------------------------------------------
-- Table `customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `paternal_last_name` VARCHAR(45) NULL,
  `maternal_last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL UNIQUE,
  `password` VARCHAR(255) NULL,
  `mobile_phone` VARCHAR(15) NULL,
  `phone` VARCHAR(15) NULL,
  `created_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB CHARSET=utf8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lu_order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lu_order_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB CHARSET=utf8;


INSERT INTO `lu_order_status` (`id`, `status`)
VALUES
  (1, 'pending'),
  (2, 'in progress'),
  (3, 'completed'),
  (4, 'cancelled');

-- -----------------------------------------------------
-- Table `lu_payment_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lu_payment_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB CHARSET=utf8;


INSERT INTO `lu_payment_type` (`id`, `type`)
VALUES
  (1, 'card'),
  (2, 'cash');

-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `order_status_id` INT NOT NULL DEFAULT 1,
  `appointment_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `comments` LONGTEXT NULL,
  `updated_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_orders_customers`
    FOREIGN KEY (`customer_id`)
    REFERENCES `customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_lu_order_status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `lu_order_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB CHARSET=utf8;


-- -----------------------------------------------------
-- Table `payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` FLOAT NULL,
  `order_id` INT NOT NULL,
  `lu_payment_type_id` INT NOT NULL,
  `status` ENUM('pending', 'paid', 'cancelled') NOT NULL DEFAULT 'pending',
  `reference` VARCHAR(100) NULL COMMENT 'Stripe session id',
  `created_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `comments` LONGTEXT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_payments_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_lu_payment_type1`
    FOREIGN KEY (`lu_payment_type_id`)
    REFERENCES `lu_payment_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB CHARSET=utf8;


-- -----------------------------------------------------
-- Table `vehicles`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `vehicles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `charge_per_kilometer` int(10) NOT NULL,
  `charge_per_floor` int(10) NOT NULL,
  `driver_fee` int(10) NOT NULL COMMENT 'driver fee',
  `loader_fee` int(10) NOT NULL COMMENT 'fee per loader',
  `loaders_quantity` int(2) NOT NULL COMMENT 'quantity of loaders',
  `size` enum('small','medium','large') DEFAULT NULL,
  `weight` varchar(45) DEFAULT NULL COMMENT 'weight in kilograms',
  `width` varchar(45) DEFAULT NULL,
  `height` varchar(45) DEFAULT NULL,
  `length` varchar(45) DEFAULT NULL,
  `brand` varchar(45) DEFAULT NULL,
  `model` varchar(45) DEFAULT NULL,
  `carrier_company_id` int(11) NOT NULL,
  `description` varchar(200) DEFAULT NULL,
  `picture` varchar(200) DEFAULT NULL,
  `plates` varchar(45) DEFAULT NULL,
  `base_address` varchar(200) DEFAULT NULL,
  `active` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `fk_carrier_company` (`carrier_company_id`),
  CONSTRAINT `fk_carrier_company` FOREIGN KEY (`carrier_company_id`) REFERENCES `carrier_company` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB CHARSET=utf8;

INSERT INTO `vehicles` (`id`, `charge_per_kilometer`, `charge_per_floor`, `driver_fee`, `loader_fee`, `loaders_quantity`, `size`, `weight`, `width`, `height`, `length`, `brand`, `model`, `carrier_company_id`, `description`, `picture`, `plates`, `base_address`, `active`)
VALUES
	(1, 25, 100, 400, 300, 2, 'small', '0–2,722', NULL, NULL, NULL, 'Chevrolet', 'Colorado/GMC Canyon', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'Chevrolet_Colorado.jpg', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 0),
	(2, 25, 100, 400, 300, 2, 'small', '0–2,722', NULL, NULL, NULL, 'Ford', 'Ranger', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'ford-ranger.webp', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1),
	(3, 25, 100, 400, 300, 2, 'small', '0–2,722', NULL, NULL, NULL, 'Nissan', 'Frontier', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'nissan-frontier.webp', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1),
	(4, 25, 100, 400, 300, 2, 'small', '0–2,722', NULL, NULL, NULL, 'Jeep', 'Comanche', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'truck-medium.svg', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1),
	(5, 25, 100, 400, 300, 2, 'small', '0–2,722', NULL, NULL, NULL, 'Toyota', 'Tacoma', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'toyota-tacoma.jpg', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1),
	(6, 25, 100, 400, 300, 2, 'small', '0–2,722', NULL, NULL, NULL, 'Honda', 'Ridgeline FWD', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'truck-medium.svg', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1),
	(7, 50, 150, 600, 300, 4, 'medium', '7,258–8,845', NULL, NULL, NULL, 'Chevrolet', 'Silverado/GMC Sierra 5500', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'chevrolet-silverado.webp', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1),
	(8, 50, 150, 600, 300, 4, 'medium', '7,258–8,845', NULL, NULL, NULL, 'Ford', 'F-550', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'ford-f550.jpeg', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1),
	(9, 50, 150, 600, 300, 4, 'medium', '7,258–8,845', NULL, NULL, NULL, 'Ram', '5500', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'ram-5500.jpg', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1),
	(10, 50, 150, 600, 300, 4, 'medium', '7,258–8,845', NULL, NULL, NULL, 'Kenworth', 'T170', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'kenworth-t170.jpg', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1),
	(11, 50, 150, 600, 300, 4, 'medium', '7,258–8,845', NULL, NULL, NULL, 'Peterbilt', '325', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'peterbilt-325.png', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1),
	(12, 50, 150, 600, 300, 4, 'medium', '7,258–8,845', NULL, NULL, NULL, 'International', 'TerraStar', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'International-terrastar.jpeg', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1),
	(13, 50, 150, 600, 300, 4, 'medium', '7,258–8,845', NULL, NULL, NULL, 'Isuzu', 'NRR', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'isuzu-nrr.jpg', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1),
	(14, 75, 200, 800, 300, 6, 'large', '11,794–14,969', NULL, NULL, NULL, 'Autocar', 'ACMD', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'autocar-acmd.jpg', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1),
	(15, 75, 200, 800, 300, 6, 'large', '11,794–14,969', NULL, NULL, NULL, 'GMC', 'C7500', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'gmc-c7500.jpg', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1),
	(16, 75, 200, 800, 300, 6, 'large', '11,794–14,969', NULL, NULL, NULL, 'Kenworth', 'T470 & T440 & T370', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'kenworth-t470.jpg', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1),
	(17, 75, 200, 800, 300, 6, 'large', '11,794–14,969', NULL, NULL, NULL, 'Peterbilt', '220 & 337', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'peterbilt-337.png', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1),
	(18, 75, 200, 800, 300, 6, 'large', '11,794–14,969', NULL, NULL, NULL, 'Ford', 'F-750', 1, 'I\'m baby drinking vinegar vape pok pok sriracha. Franzen kale chips trust fund vexillologist, activated charcoal snackwave sriracha keytar. Mixtape hella lumbersexual, flexitarian literally freegan PB', 'ford-f750.jpg', '464gfg', 'Ejido de Guadalupe 54745 Cuautitlan Izcalli México', 1);


-- -----------------------------------------------------
-- Table `products`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `vehicle_id` int(11) NOT NULL,
  `price` float DEFAULT NULL,
  `total_kilometers` int(20) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `active` tinyint(4) NOT NULL,
  `updated_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_date` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_vehicle1` (`vehicle_id`),
  CONSTRAINT `fk_vehicle1` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicles` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB CHARSET=utf8;


-- -----------------------------------------------------
-- Table `calculated_distance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calculated_distance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address_origin` VARCHAR(200) NULL,
  `address_destination` VARCHAR(200) NULL,
  `kilometers` INT(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB CHARSET=utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;