FROM python:3.11-alpine
WORKDIR /chalan
COPY . .

RUN pip install --upgrade pip
RUN apk update && apk add --no-cache tzdata
ENV TZ America/Lima
RUN apk add python3-dev \
                    gcc \
                    libc-dev \
                    libffi-dev \
                    postgresql-dev

RUN pip install -r requirements/prod.txt
