FROM python:3.8.10-alpine
WORKDIR /chalan
COPY ./requirements/ requirements/

RUN apk add --no-cache tzdata
ENV TZ America/Mexico_City
RUN apk update && apk add python3-dev \
                          gcc \
                          libc-dev \
                          libffi-dev

RUN pip install -r requirements/dev.txt

CMD ["flask", "run", "--host=0.0.0.0", "--port=8001"]