FROM python:3.11-alpine
WORKDIR /chalan
COPY ./requirements/ requirements/

RUN pip install --upgrade pip
RUN apk add --no-cache tzdata
ENV TZ America/Mexico_City
RUN apk update && apk add python3-dev \
                          gcc \
                          libc-dev \
                          libffi-dev \
                          postgresql-dev

RUN pip install -r requirements/dev.txt

CMD ["flask", "run", "--host=0.0.0.0", "--port=8001"]